# Generated by Django 3.1.7 on 2021-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='lat',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='long',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
