# Generated by Django 3.1.7 on 2021-03-16 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210316_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement_Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('long', models.CharField(default='unknown', max_length=200)),
                ('lat', models.CharField(default='unknown', max_length=200)),
                ('id_sellertype', models.ForeignKey(on_delete=models.SET('unknown'), to='order.seller_type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_mail', models.CharField(max_length=30)),
                ('total_price', models.IntegerField(default=0)),
                ('delivery_fees', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=5)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_duration', models.DateTimeField()),
                ('order_time', models.DateTimeField()),
                ('order_duration', models.DateTimeField()),
                ('order_type', models.CharField(max_length=20)),
                ('is_paid', models.BooleanField()),
                ('distance', models.FloatField()),
                ('state', models.CharField(max_length=10)),
                ('id_buyer', models.ForeignKey(on_delete=models.SET('unknown'), to='order.buyer')),
                ('id_payement', models.ForeignKey(on_delete=models.SET('unknown'), to='order.payement_methods')),
                ('id_seller', models.ForeignKey(on_delete=models.SET('unknown'), to='order.seller')),
                ('id_user', models.ForeignKey(on_delete=models.SET('unknown'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
