# Generated by Django 3.1.7 on 2021-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payement_methods_seller_seller_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('id_order', models.ForeignKey(on_delete=models.SET('unknown'), to='order.order')),
            ],
        ),
    ]
