# Generated by Django 3.1.7 on 2021-03-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210324_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_duration',
        ),
    ]
