# Generated by Django 3.1.7 on 2021-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_order_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_duration',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
