# Generated by Django 3.1.7 on 2021-03-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210331_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accept_time',
            field=models.DateTimeField(null=True),
        ),
    ]
