# Generated by Django 3.1.6 on 2021-04-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210415_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Long',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Vehicle',
            new_name='vehicle',
        ),
    ]
