# Generated by Django 3.1.6 on 2021-04-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210415_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='images/'),
        ),
    ]
