# Generated by Django 3.1.6 on 2021-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210416_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
