# Generated by Django 3.1.6 on 2021-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20210421_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='buyer_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
