# Generated by Django 3.1.6 on 2021-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_block_buyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
