# Generated by Django 3.1.6 on 2021-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_feedback_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivered_orders',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failed_orders',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profits',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
