# Generated by Django 3.1.6 on 2021-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20210423_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivered_orders',
            field=models.IntegerField(default=0, max_length=12,null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='failed_orders',
            field=models.IntegerField(default=0, max_length=12,null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profits',
            field=models.FloatField(default=0, max_length=12,null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(default=0, max_length=12,null=True),
        ),
    ]
