# Generated by Django 3.1.6 on 2021-04-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20210423_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
